### PR TITLE
Bump Ginga to 2.6.6

### PR DESCRIPTION
**Pull request by pllim**
@ejeschke and @bsipocz -- Does this look okay?

c/c @sosey 

p.s. Who is `pbvarga1`? Should this person be removed?

### CODE REVIEW

**Comment by bsipocz** [comment]
@pllim - @mwcraig added him here: https://github.com/conda-forge/staged-recipes/pull/3346 (triggered by this I believe https://github.com/conda-forge/staged-recipes/pull/3340)

**Comment by bsipocz** [comment]
@pllim - @mwcraig added him here: https://github.com/conda-forge/staged-recipes/pull/3346 (triggered by this I believe https://github.com/conda-forge/staged-recipes/pull/3340)

**Comment by mwcraig** [comment]
@pllim -- he was at pyastro17, was willing to help with updates.

**Comment by mwcraig** [comment]
@pllim -- any objection to changing this to a `noarch` package? That would mean it is installable only for conda 4.3 or higher (the first 4.3 release was about 11 months ago), but it would vastly reduce build times because builds would happen on circleCI instead of travis.

**Comment by mwcraig** [comment]
If you are ok with that, then copy and paste this in a comment on this pull request: `@conda-forge-admin, please add noarch: python`

**Comment by mwcraig** [comment]
oops...looks like the conda-forge bot was not fooled by backticks and converted this to `noarch`. If that is ok please go ahead and merge, otherwise we'll need to revert the change

**Comment by ejeschke** [comment]
As far as I understand it, noarch should be fine. Ginga is a pure python
package.

~E

**Comment by mwcraig** [comment]
Excellent, merged! I'm working on getting ipyevents into conda-forge...

**Comment by pllim** [comment]
Thanks, everyone!

**Pull request merged**
