### PR TITLE
Release Ginga v3.0.0 into the wilds of conda-forge

### PR DESCRIPTION
**Pull request by ejeschke**
Checklist
* [X] Reset the build number to `0` (if the version changed)
* [X] Ensured the license file is being packaged.

New release.

### CODE REVIEW

**Comment by ejeschke** [comment]
@mwcraig, @bsipocz, any idea about the CircleCI test failure here?  Appreciate it if you could have a quick look! Thanks.

**Comment by mwcraig** [comment]
I think the recipe needs a re-render because noarch builds are no longer done on circleCI. So, @conda-forge-admin please rerender

**Comment by mwcraig** [comment]
There are also some changes needed to the recipe, so even if this passes please don't merge quite yet. About to review...

**Comment by mwcraig** [comment]
I think this is good, so merging. Congrats on the 3.0 release!

**Comment by ejeschke** [comment]
Many thanks, @mwcraig!

**Pull request merged**
