### PR TITLE
Fix for broken CI build

### PR DESCRIPTION
**Pull request by ejeschke**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Fixes for errors thrown by automated stock builder

### CODE REVIEW

**Comment by ejeschke** [comment]
@pllim, @mwcraig, @bsipocz, I think this fixes the pipeline errors.  Ok, to merge?

**Comment by mwcraig** [comment]
@conda-forge-bot, please rerender

**Comment by mwcraig** [comment]
Let's see what happens when the bot re-renders it.

**Comment by pllim** [comment]
Is this a duplicate of  #13 ?

**Comment by pllim** [comment]
I copied the rest of the recipe changes here to #13. I propose we close this in favor of #13.

**Comment by ejeschke** [comment]
> I copied the rest of the recipe changes here to #13. I propose we close this in favor of #13.

Fine by me.

**Pull request closed without merging**
