### PR TITLE
Make Ginga release v4.1.1

### PR DESCRIPTION
**Pull request by ejeschke**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Review by pllim — APPROVED** [review]
Just a bug fix, so should be ok.

**Comment by pllim** [comment]
@ejeschke , I am surprised you have to manually do this. Does conda-forge not pick up from PyPI automatically for you?

**Comment by pllim** [comment]
@conda-forge-admin, please rerender

**Comment by pllim** [comment]
(Hmm I guess the rerender is not doing anything? I was just trying to see if it would update the build infrastructure.)

**Comment by ejeschke** [comment]
@pllim, it used to, I remember. But I have it in my notes that I have to follow these steps now. Would be glad to learn more about this--but I'm relying on your collective expertise!

**Comment by pllim** [comment]
@ejeschke , does the job list here look right? You only have Linux build?

**Comment by ejeschke** [comment]
@pllim, LGTM?

**Comment by pllim** [comment]
I guess it is okay... If not, hopefully @mwcraig can advise. 🙏

**Comment by ejeschke** [comment]
> You only have Linux build?

I think so (?). Ginga is a pure Python package so it shouldn't be necessary to do multiple platforms, right?

**Comment by ejeschke** [comment]
I've merged the last few with no issues.

**Comment by pllim** [comment]
Okay then, feel free to merge. Thanks!

**Comment by ejeschke** [comment]
> @ejeschke , I am surprised you have to manually do this. Does conda-forge not pick up from PyPI automatically for you?

I guess it is just kind of slow--I just got the PR now, couple of hours later.

**Pull request merged**
