### PR TITLE
Updates for release v3.4.0

### PR DESCRIPTION
**Pull request by ejeschke**
Checklist
* [ x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ejeschke** [comment]
@conda-forge-admin, please rerender

**Comment by ejeschke** [comment]
@pllim, @bsipocz, @mwcraig, thank you for your oversight!  All LGTM?

**Review by pllim — APPROVED** [review]
LGTM. Thanks!

**Comment by pllim** [comment]
Did you create this manually? I thought conda-forge usually auto PR from PyPI release.

**Comment by ejeschke** [comment]
> Did you create this manually? I thought conda-forge usually auto PR from PyPI release.

I thought so too, but I needed to change my conda-feedstock master to main, then pull/merge updates anyway, so maybe it didn't happen automatically.  In any case, it seems happy now.

**Pull request merged**
