### PR TITLE
maintenance release 3.0.1 for pip install issue

### PR DESCRIPTION
**Pull request by ejeschke**

### CODE REVIEW

**Comment by bsipocz** [comment]
@ejeschke - I would rather go ahead with the bot's PR, #9, as it also includes some infrastructural clean ups.

**Comment by ejeschke** [comment]
@bsipocz, that sounds fine with me. I defer to the feedstock experts!

**Comment by bsipocz** [comment]
I'm not expert at all, thus would leave it to the bot. It usually does the magic automatically 😉 (and it usually opens a PR quite quickly (within an hour max) after a pypi release is done)

**Comment by ejeschke** [comment]
> (and it usually opens a PR quite quickly (within an hour max) after a pypi release is done)

Indeed it did!  And I was baffled what it was I was receiving until you explained it.  Impressed with the bot service!

**Comment by ejeschke** [comment]
@bsipocz, just for my reference, I take it this means in the future I should just push the PyPI package and let the bot respond with the PR, rather than by submitting a new PR manually?

**Comment by bsipocz** [comment]
Yes. And as you're code owner for the feedstock you'll be pinged about the PR. 
Then my rule of thumb is to merge it when it's all green CI wise (sometimes there are hundreds of lines of changes in the machinery. I've given up to follow what goes on in there, but simply trust in the conda-forge devs that it's the sensible way to go).

**Pull request closed without merging**
